### ISSUE TITLE
Extend YNL to support netlink-raw families

### ISSUE THREAD

**Issue by maryamtahhan** [redhat-et/ekho#11]
YNL currently support generic Netlink. A number of core changes are required in order to support netlink-raw as the message format differs from generic netlink.

The goal of this task is to extend YNL to support raw netlink and to push the resulting patches to the kernel

**Comment by maryamtahhan** [comment]
[Patch-set](https://patchwork.kernel.org/project/netdevbpf/cover/20230725162205.27526-1-donald.hunter@gmail.com/) submitted to the Kernel

**Comment by donaldh** [comment]
https://git.kernel.org/pub/scm/linux/kernel/git/netdev/net-next.git/commit/?id=e46dd903efe367214802b8d1cac01bdc43708339
