### ISSUE TITLE
Extend YNL to add specs for addr and route rtnetlink message types

### ISSUE THREAD

**Issue by maryamtahhan** [redhat-et/ekho#12]
Add netlink-raw specs to YNL for the following rtnetlink messages:
 - newaddr, deladdr, getaddr (dump)
 - getroute (dump)
 
 DOD patches submitted to the Kernel

**Comment by maryamtahhan** [comment]
[Patchset](https://patchwork.kernel.org/project/netdevbpf/patch/20230725162205.27526-4-donald.hunter@gmail.com/) submitted to the Kernel

**Comment by donaldh** [comment]
https://git.kernel.org/pub/scm/linux/kernel/git/netdev/net-next.git/commit/?id=dfb0f7d9d979567ad7b1194093e649c7a0d42f90
https://git.kernel.org/pub/scm/linux/kernel/git/netdev/net-next.git/commit/?id=b2f63d904e7254de447e6e809fc6ebd98323aa39
https://git.kernel.org/pub/scm/linux/kernel/git/netdev/net-next.git/commit/?id=023289b4f582820f3124fa7ff42a61959fe7dea6
